<?php

namespace Database\Seeders;

use App\Models\Patient;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;

class PatientsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $patients = [
            [
                'patient_id' => 1,
                'first_name' => 'John',
                'last_name' => 'Doe',
                'gender' => 'M',
                'birth_date' => '1995-03-15',
                'city' => 'Dhaka',
                'province_id' => 'DN',
                'allergies' => 'Peanuts',
                'height' => '5.9 ft',
                'weight' => 75,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'patient_id' => 2,
                'first_name' => 'Jane',
                'last_name' => 'Smith',
                'gender' => 'F',
                'birth_date' => '1989-07-22',
                'city' => 'Chattogram',
                'province_id' => 'CT',
                'allergies' => 'NKA',
                'height' => '5.5 ft',
                'weight' => 60,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'patient_id' => 3,
                'first_name' => 'Rahim',
                'last_name' => 'Uddin',
                'gender' => 'M',
                'birth_date' => '1980-01-10',
                'city' => 'Khulna',
                'province_id' => 'KH',
                'allergies' => null,
                'height' => '5.8 ft',
                'weight' => 80,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'patient_id' => 4,
                'first_name' => 'Karim',
                'last_name' => 'Ali',
                'gender' => 'M',
                'birth_date' => '1975-11-30',
                'city' => 'Rajshahi',
                'province_id' => 'RJ',
                'allergies' => 'Dust',
                'height' => '6.0 ft',
                'weight' => 85,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'patient_id' => 5,
                'first_name' => 'Fatema',
                'last_name' => 'Begum',
                'gender' => 'F',
                'birth_date' => '1992-06-05',
                'city' => 'Sylhet',
                'province_id' => 'SY',
                'allergies' => 'Pollen',
                'height' => '5.4 ft',
                'weight' => 55,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'patient_id' => 6,
                'first_name' => 'Hasan',
                'last_name' => 'Mahmud',
                'gender' => 'M',
                'birth_date' => '1985-09-18',
                'city' => 'Barishal',
                'province_id' => 'BR',
                'allergies' => 'Seafood',
                'height' => '5.7 ft',
                'weight' => 70,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'patient_id' => 7,
                'first_name' => 'Nusrat',
                'last_name' => 'Jahan',
                'gender' => 'F',
                'birth_date' => '1998-12-12',
                'city' => 'Dhaka',
                'province_id' => 'DN',
                'allergies' => null,
                'height' => '5.3 ft',
                'weight' => 50,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'patient_id' => 8,
                'first_name' => 'Sabbir',
                'last_name' => 'Hossain',
                'gender' => 'M',
                'birth_date' => '1990-02-20',
                'city' => 'Gazipur',
                'province_id' => 'GA',
                'allergies' => 'Gluten',
                'height' => '5.9 ft',
                'weight' => 78,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'patient_id' => 9,
                'first_name' => 'Mim',
                'last_name' => 'Akter',
                'gender' => 'F',
                'birth_date' => '1996-05-07',
                'city' => 'Narayanganj',
                'province_id' => 'NA',
                'allergies' => 'NKA',
                'height' => '5.2 ft',
                'weight' => 52,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'patient_id' => 10,
                'first_name' => 'Arif',
                'last_name' => 'Khan',
                'gender' => 'M',
                'birth_date' => '1988-08-14',
                'city' => 'Cumilla',
                'province_id' => 'CU',
                'allergies' => 'Nuts',
                'height' => '6.1 ft',
                'weight' => 82,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'patient_id' => 11,
                'first_name' => 'Shila',
                'last_name' => 'Rani',
                'gender' => 'F',
                'birth_date' => '1993-04-25',
                'city' => 'Rangpur',
                'province_id' => 'RP',
                'allergies' => 'NKA',
                'height' => '5.5 ft',
                'weight' => 57,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'patient_id' => 12,
                'first_name' => 'Imran',
                'last_name' => 'Ahmed',
                'gender' => 'M',
                'birth_date' => '1987-10-03',
                'city' => 'Bogura',
                'province_id' => 'BG',
                'allergies' => null,
                'height' => '5.8 ft',
                'weight' => 76,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'patient_id' => 13,
                'first_name' => 'Tania',
                'last_name' => 'Islam',
                'gender' => 'F',
                'birth_date' => '1999-01-15',
                'city' => 'Jessore',
                'province_id' => 'JS',
                'allergies' => 'Dust',
                'height' => '5.3 ft',
                'weight' => 53,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'patient_id' => 14,
                'first_name' => 'Rashed',
                'last_name' => 'Mia',
                'gender' => 'M',
                'birth_date' => '1978-07-09',
                'city' => 'Mymensingh',
                'province_id' => 'MY',
                'allergies' => 'Seafood',
                'height' => '5.9 ft',
                'weight' => 81,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'patient_id' => 15,
                'first_name' => 'Sumaiya',
                'last_name' => 'Akter',
                'gender' => 'F',
                'birth_date' => '2000-06-20',
                'city' => 'Dhaka',
                'province_id' => 'DN',
                'allergies' => 'Pollen',
                'height' => '5.1 ft',
                'weight' => 49,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'patient_id' => 16,
                'first_name' => 'Mahmudul',
                'last_name' => 'Hasan',
                'gender' => 'M',
                'birth_date' => '1983-03-11',
                'city' => 'Pabna',
                'province_id' => 'PB',
                'allergies' => null,
                'height' => '6.0 ft',
                'weight' => 83,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'patient_id' => 17,
                'first_name' => 'Ritu',
                'last_name' => 'Das',
                'gender' => 'F',
                'birth_date' => '1994-09-28',
                'city' => 'Dinajpur',
                'province_id' => 'DP',
                'allergies' => 'NKA',
                'height' => '5.4 ft',
                'weight' => 56,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'patient_id' => 18,
                'first_name' => 'Sohel',
                'last_name' => 'Rana',
                'gender' => 'M',
                'birth_date' => '1986-11-05',
                'city' => 'Tangail',
                'province_id' => 'TG',
                'allergies' => 'Dust',
                'height' => '5.9 ft',
                'weight' => 77,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'patient_id' => 19,
                'first_name' => 'Anika',
                'last_name' => 'Chowdhury',
                'gender' => 'F',
                'birth_date' => '1997-02-17',
                'city' => 'Feni',
                'province_id' => 'FN',
                'allergies' => 'Nuts',
                'height' => '5.3 ft',
                'weight' => 51,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'patient_id' => 20,
                'first_name' => 'Jahid',
                'last_name' => 'Hasan',
                'gender' => 'M',
                'birth_date' => '1979-05-12',
                'city' => 'Noakhali',
                'province_id' => 'NK',
                'allergies' => 'Seafood',
                'height' => '6.1 ft',
                'weight' => 85,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ]
        ];
        Patient::insert($patients);
    }
}
